### ISSUE TITLE
CloudBot (Gonzobot Branch) loads plugins even if they are in disabled_plugins[]

### ISSUE THREAD

**Issue by gtwy** [snoonetIRC/CloudBot#117]
Example from config.json:
```
            "disabled_plugins": [
                "animal_gifs",
                "attacks",
                "badwords",
                "bible",
                "cats"
```

Example from starting gonzobot:
```

[14:19:19] [INFO] Loaded command bible/passage from bible.py
[14:19:19] [INFO] Loaded command cats from cats.py
[14:19:19] [INFO] Loaded command doggifs from animal_gifs.py
[14:16:33] [INFO] Registering tables for badwords

```

It loads all 77 plugins that I have disabled...

Edit: having looked through plugin.py, it looks like there is a whitelist and a blacklist. I'll see if I can get this working with whitelist. In the meantime, I'm humbly requesting that these two lines all be changed to indicate whitelist/blacklist instead of "disabled_plugins":

https://github.com/snoonetIRC/CloudBot/blob/9455941ffd7d2cbf2b1a3bb6ed63e3e261194629/cloudbot/plugin.py#L121
https://github.com/snoonetIRC/CloudBot/blob/9455941ffd7d2cbf2b1a3bb6ed63e3e261194629/cloudbot/plugin.py#L143

**Comment by linuxdaemon** [comment]
This functionality was removed 4 years ago and the comments were just never updated. It was removed in f08bd70876e576b07377d57dc675239f1f7090f3 .
