### ISSUE TITLE
.syn command returns URL encoding when used incorrectly

### ISSUE THREAD

**Issue by Jessexd** [snoonetIRC/CloudBot#213]
Notice how it returns `%20` for space.

```
desgen  ╡.syn busting balls
<bot> ╡ (desgen) Sorry, I couldn't find any synonyms for busting%20balls.
```

**Suggestion:**
Disallow more then one word being used, and if a user does, return the correct syntax usage help:
`<bot> ╡ .syn <word> - Returns a list of synonyms for <word>.`
Or, alternatively:
`<bot> ╡ Only one word can be specified.`
**Small note:**
Noticed the help command doesn't have anything for .syn, old plugin?

**Comment by linuxdaemon** [comment]
> Small note:
> Noticed the help command doesn't have anything for .syn, old plugin?

Please elaborate

**Comment by Jessexd** [comment]
@linuxdaemon 
Typing `.help syn` returns `Unknown command 'syn'`

**Comment by linuxdaemon** [comment]
I have made a separate issue #214 for that as it is not specific to the wordnik plugin
