### ISSUE TITLE
duckhunt.py is outputting "channels" twice

### ISSUE THREAD

**Issue by ghost** [snoonetIRC/CloudBot#222]
Via [line 642](https://github.com/snoonetIRC/CloudBot/blob/4fa4a95341f47e2f03698776f691c618f357d0ac/plugins/duckhunt.py#L642), .ducks is printing the word channels twice.

Example:

> PineApple's duck stats: 2 ducks killed and 499 ducks befriended in #mturkrefugees. Across 3 **channels channels**: 4 ducks killed and 1,631 ducks befriended. Averaging 1 kill and 543 friends per channel.

**Comment by duckspike** [comment]
Swore there was a PR open for this already. I'll make sure it's taken care of.

**Comment by linuxdaemon** [comment]
@duckspike there is edwardslabs/CloudBot#244 but I don't think @edwardslabs ever got around to handling the PRs on that repo.
