### ISSUE TITLE
Auto reload plugins on change?

### ISSUE THREAD

**Issue by Violet-Vibes** [snoonetIRC/CloudBot#236]
How can I auto reload any plugins thats been changed? Currently I have to manually reload them using !pluginload plugins/plugin.py

**Comment by weylin** [comment]
In your config file you can set `plugin_reloading` to `true`. 
https://github.com/edwardslabs/CloudBot/blob/gonzobot/config.default.json#L122

**Comment by Violet-Vibes** [comment]
It's set to true but plugins does not automatically reload. I've tried
restarting the bot completely

Den sön 13 maj 2018 22:55Weylin <notifications@github.com> skrev:

**Comment by linuxdaemon** [comment]
@Chiisato Please include a copy of your `config.json` file (with passwords and similar removed).

**Comment by Chiisato** [comment]
`{
    "connections": [
        {
            "name": "quakenet",
            "type": "irc",
            "connection": {
                "server": "irc.quakenet.org",
                "port": 6667,
                "ssl": false,
                "ignore_cert": true,
                "password": "",
                "timeout": 300
            },
            "ping_settings": {
                "interval": 60,
                "warn": 120,
                "timeout": 300
            },
            "nick": "VOIDED",
            "user": "VOIDED",
			"realname": "VOIDED",
            "avoid_notices": false,
            "channels": [
               "#VOIDED",
			   "#VOIDED",
               "#VOIDED"
            ],
            "disabled_commands": [],
            "acls": {},
			"sasl": {
                "enabled": false,
                "mechanism": "PLAIN",
                "user": "",
                "pass": ""
            },
            "nickserv": {
                "enabled": true,
                "nickserv_password": "VOIDED",
                "nickserv_user": "VOIDED",
                "nickserv_name": "Q@CServe.quakenet.org",
                "nickserv_command": "auth"
            },
            "ratelimit": {
                "max_tokens": 17.5,
                "restore_rate": 2.5,
                "message_cost": 5,
                "strict": true
            },
            "permissions": {
                "admins": {
                    "perms": [
                        "addfactoid",
                        "delfactoid",
                        "ignore",
                        "botcontrol",
                        "plpaste",
                        "permissions_users",
                        "op"
                    ],
                    "users": [
                        "VOIDED"
                    ]
                },
                "moderators": {
                    "perms": [
                        "addfactoid",
                        "delfactoid",
                        "ignore"
                    ],
                    "users": [
                    ]
                }
            },
            "plugins": {},
            "command_prefix": "!"
        }
    ],
    "api_keys": {
        "tvdb": "",
        "destiny": "VOIDED",
        "bing_azure": "",
        "wolframalpha": "VOIDED",
        "lastfm": "",
        "rottentomatoes": "",
        "soundcloud": "VOIDED",
        "twitter_consumer_key": "VOIDED",
        "twitter_consumer_secret": "VOIDED",
        "twitter_access_token": "VOIDED",
        "twitter_access_secret": "VOIDED",
        "imgur_client_id": "VOIDED",
        "imgur_client_secret": "VOIDED",
        "wunderground": "VOIDED",
        "rdio_key": "",
        "rdio_secret": "",
        "google_dev_key": "VOIDED",
        "google_cse_id": "VOIDED",
        "octopart": "",
        "brewerydb": "VOIDED",
        "spotify_client_id": "VOIDED",
        "spotify_client_secret": "VOIDED",
        "wordnik": ""
    },
    "database": "sqlite:///cloudbot.db",
    "plugin_loading": {
        "use_whitelist": false,
        "blacklist": [
            "update"
        ],
        "whitelist": []
    },
    "web": {
      "enabled": false,
      "address": "0.0.0.0",
      "port": 8090,
      "bot_name": "CloudBot"
    },
    "reloading": {
        "config_reloading": true,
        "plugin_reloading": true
    },
    "logging": {
        "console_debug": true,
        "file_debug": false,
        "show_plugin_loading": true,
        "show_motd": true,
        "show_server_info": true,
        "raw_file_log": false,
        "file_log": true
    }
}
`

**Comment by linuxdaemon** [comment]
Use a [pastebin](https://pastebin.com) or a [gist](https://gist.github.com), do not post entire files in a comment

**Comment by Violet-Vibes** [comment]
Sorry, https://pastebin.com/85kbJawj

**Comment by linuxdaemon** [comment]
Are you using the latest version from the `gonzobot` branch on this repo? https://github.com/snoonetIRC/CloudBot

**Comment by Violet-Vibes** [comment]
Correct

**Comment by linuxdaemon** [comment]
Please provide a log of the console surrounding when a plugin file was modified and the auto reload should have occurred

**Comment by Violet-Vibes** [comment]
sorry for delaying, restarting the host fixed this issue
