### ISSUE TITLE
LIKE operator causing problems with underscores in usernames when using .seen command

### ISSUE THREAD

**Issue by joriskcf** [snoonetIRC/CloudBot#24]
Checking when users were last online using the `.seen <nick>` command, the [LIKE](https://github.com/snoonetIRC/CloudBot/blob/gonzobot/plugins/history.py#L106) operator is used in the database lookup. This causes problems when people have underscores in their IRC nicks, because the LIKE operator uses the underscore as a single-character wildcard. In our case, this caused `.seen justin_timeforcake` to return the output for `justin-timeforcake`.

If the LIKE operator was being used to allow wildcard searching, a simple solution might be to use GLOB instead.

**Comment by edwardslabs** [comment]
Thanks for the suggestion, I will take a look at either switchign to GLOB or excaping `_` in nicks.
