### ISSUE TITLE
.time command doesn't take time zones as an argument

### ISSUE THREAD

**Issue by vurp0** [snoonetIRC/CloudBot#3]
It would make sense to be able to use a time zone as argument to the .time command. Some simple format like "UTC+3" would suffice for me, but people in the US might prefer to use time zone names like "EET", "CST" and so on.

If I get the time and interest I might make a pull request myself.

**Comment by edwardslabs** [comment]
Currently the time plugin accepts a location as an argument rather than a timezone. I think it should be easy to add the requested functionality. I will take a look.

**Comment by edwardslabs** [comment]
4cc3fd572a1001da5c931cb9a0f444bcf0ab10e8 adds support for UTC offset as an input. 

I decided against supporting timezone abbreviations as there are too many duplicates (ex. CST can be UTC+8, UTC-6, or UTC-5.)
