### ISSUE TITLE
Removal of python 3.4 support

### ISSUE THREAD

**Issue by linuxdaemon** [snoonetIRC/CloudBot#321]
Many libraries (eg. `yarl`) have begun dropping python 3.4 support to support type hinting. The final release of 3.4 is also expected in March 2019. If we can migrate away from supporting 3.4 it will allow us to use newer features and syntax as well as updated libraries.

Are there any major drawbacks to dropping 3.4 support? Does anyone even run 3.4 anymore?

**Comment by A-UNDERSCORE-D** [comment]
3.4 from what Ive seen is like the 1.9 version of minecraft. used while it was there and as soon as something better came out it was dropped. I think the gains from dropping it (real type hinting, or the start thereof) are worth most issues. We may want to consider 3.5 as well, though thats held onto a lot more than 3.4 is.

**Comment by linuxdaemon** [comment]
3.5 is still the default on many operating systems, including Ubuntu 16.04. It won't be dropped soon.

**Comment by A-UNDERSCORE-D** [comment]
Well, for a later discussion then. That said, I don't think we will run into any major issues losing 3.4 and should go ahead with doing so.

**Comment by linuxdaemon** [comment]
It appears pytest 5.0 will be dropping 3.4 support as well, so I guess that answers the question.
