### ISSUE TITLE
Dogpile cert errors

### ISSUE THREAD

**Issue by linuxdaemon** [snoonetIRC/CloudBot#344]
```
Error occurred in dogpile.dogpileimage
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.dogpile.com', port=443): Max retries exceeded with url: /search/images?<query> (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))
```
It seems dogpile's CA isn't trusted by default on Ubuntu, not sure how we want to fix this temporarily or what

**Comment by Shadeblast** [comment]
As per https://www.ssllabs.com/ssltest/analyze.html?d=www.dogpile.com this is _technically_ a mis-configuration on Dogpile's end as they don't supply the full chain.

Options:
- Importing the CA cert (DigiCert SHA2 Secure Server CA) into the host.
- Shoot Dogpile a message requesting they provide the entire chain in their webserver.
- (Unsecure, plsno) Disabling SSL verification in CloudBot (for this module?).

**Comment by linuxdaemon** [comment]
@Shadeblast Could you contact dogpile/infospace about the issue? That seems to be the best option for now

**Comment by Shadeblast** [comment]
@linuxdaemon I've filled out the InfoSpace Holdings contact form with a description of the issue. I'll keep you posted.

**Comment by GaeaKat** [comment]
Should we maybe disable the SSL temp for this module's call only , but leave an error message in the log channel, so we know it is still going on, and not to be forgotten about?

**Comment by linuxdaemon** [comment]
If we were going to do that, I think the better option would be disabling SSL verification so the connection is at least still encrypted. Currently waiting for @Shadeblast to hear back from Dogpile about the issue

**Comment by GaeaKat** [comment]
Sorry, is what I meant but lacked the words

**Comment by Shadeblast** [comment]
@linuxdaemon No word yet. I doubt they'll respond until Monday or even Tuesday. Maybe disabling verification of SSL certs is a valid option for the moment.

**Comment by Shadeblast** [comment]
Send a follow up message as I haven't received word from them yet.

**Comment by Shadeblast** [comment]
@linuxdaemon As I still haven't heard anything (and I doubt we will), I'd suggest we go with disabling SSL verification for this module.

**Comment by linuxdaemon** [comment]
I believe https://bugs.launchpad.net/ubuntu/+source/ca-certificates/+bug/1795242 is related, I'm unable to find a way to make the cert verification accept a different CA file, I think the only option for now would be disabling verification completely for that specific request. @A-UNDERSCORE-D thoughts?

**Comment by A-UNDERSCORE-D** [comment]
There are five solutions that I can see here:

1. We disable verification globally
2. We disable verification only in the plugin
3. We make the plugin use non-secure comms with dogpile
4. We wait for dogpile and cannonical to unbreak this
5. We add the missing certs to the host for gonzo.

1 just plain isn't going to happen.

2 works but if we do that we need to check at least once a week for when it's fixed. Hell, its as good as doing 3, because it results in essentially the same vulnerability.

4 is what we're currently doing, and we could continue doing so.

5 Is the best option *for us* but it does not fix other boxes with the same issue.

So for us its a toss up between 4 and 5. I'm leaning towards 5 as its the most secure option. We should **not** disable verification anywhere if we can help it. With that in mind I think 5 is the best solution. 5 also comes with no code changes.

**Comment by linuxdaemon** [comment]
5 doesn't work, I did that locally, did not work.

**Comment by A-UNDERSCORE-D** [comment]
What certstore is it using that it did not work?

**Comment by Shadeblast** [comment]
>@A-UNDERSCORE-D 
> 5. We add the missing certs to the host for gonzo.

I've tested this on a fresh Ubuntu box with curl. Initial error is:
`curl: (60) SSL certificate problem: unable to get local issuer certificate`

Running the commando's:
`wget -O /tmp/DigiCertSHA2SecureServerCA.crt https://dl.cacerts.digicert.com/DigiCertSHA2SecureServerCA.crt`

`sudo openssl x509 -in /tmp/DigiCertSHA2SecureServerCA.crt -inform DER \`
`-out /tmp/DigiCertSHA2SecureServerCA.pem -outform PEM`

`sudo cp -uv DigiCertSHA2SecureServerCA.pem /etc/ssl/certs`

`sudo c_rehash`

This leads to a successful curl.

---------------------

Now, as the above isn't the cleanest solution (just for testing purposes), another option would be to create a directory for extra certificates.

`sudo mkdir /usr/local/share/ca-certificates/gonzobotsearchmodule`

`wget -O /tmp/DigiCertSHA2SecureServerCA.crt https://dl.cacerts.digicert.com/DigiCertSHA2SecureServerCA.crt`

`sudo openssl x509 -in /tmp/DigiCertSHA2SecureServerCA.crt -inform DER \`
`-out /tmp/DigiCertSHA2SecureServerCA.pem -outform PEM`

`sudo mv /tmp/DigiCertSHA2SecureServerCA.pem /usr/local/share/ca-certificates/gonzobotsearchmodule/DigiCertSHA2SecureServerCA.crt`

^Notice the .crt at the end here during the move.

`sudo chmod 755 /usr/local/share/ca-certificates/gonzobotsearchmodule`
`sudo chmod 644 /usr/local/share/ca-certificates/gonzobotsearchmodule/DigiCertSHA2SecureServerCA.crt`

`sudo update-ca-certificates`

**Comment by Shadeblast** [comment]
> Add dogpile certs to handle temporary cert errors - #388 

Above fixed it. Missed that.
