### ISSUE TITLE
Weather Underground does not provide API keys anymore

### ISSUE THREAD

**Issue by duckspike** [snoonetIRC/CloudBot#366]
As the title states, you can no longer obtain an API key for WeatherUnderground from their website. If you visit https://www.wunderground.com/weather/api/ , there is a splash informing to seek an alternative.

**Comment by ctburley** [comment]
There is Dark Sky,
https://darksky.net/dev
1k calls a day free $0.0001 a call after that 

[Bonus Content!](https://github.com/ctburley/akesho-irc3/blob/master/plugins/weather.py)
