### ISSUE TITLE
Removal of whois.py

### ISSUE THREAD

**Issue by linuxdaemon** [snoonetIRC/CloudBot#416]
The `pythonwhois` library this plugin depends on has been dormant for almost 5 years and is rife with issues, especially with future compatibility.

Unless someone wants to rewrite the plugin to use a different library or something, I think the best option would be to retire it.

**Comment by A-UNDERSCORE-D** [comment]
How well used is that plugin? I don't think  I've personally seen anyone use it.

**Comment by linuxdaemon** [comment]
Appears to be rarely used

**Comment by A-UNDERSCORE-D** [comment]
Sounds good to be dropped then, though wait a week and see if anyone else responds

**Comment by linuxdaemon** [comment]
@A-UNDERSCORE-D Any objections to removal? No response in 22 days from anyone
