### ISSUE TITLE
weather.py

### ISSUE THREAD

**Issue by sacredland** [snoonetIRC/CloudBot#556]
I got that error with weather.py but from eggdrop my API work A1 on darksky
<Cloud> Error occurred in weather.weather
<Cloud> googlemaps.exceptions.ApiError: REQUEST_DENIED (This API project is not authorized to use this API.)
<Cloud> Traceback: Unable to paste data
 <Cloud> Event: Unable to paste data

**Comment by linuxdaemon** [comment]
You need a google developer API key as well with the proper permissions for the geocode api
