### ISSUE TITLE
bing return error

### ISSUE THREAD

**Issue by sacredland** [snoonetIRC/CloudBot#558]
When using .bing command, with any of the two api key given by azure, I always got that:
<Cloud> Error occurred in bing.bing
 <Cloud> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.datamarket.azure.com', port=443): Max retries exceeded with url: /Bing/Search/v1/Composite?%24format=json&Query=%27spotify%27&Adult=%27Moderate%27&Sources=%27web%27 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc74dddd2e8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
<Cloud> Traceback: https://hastebin.com/sunesikoqo.txt
<Cloud> Event: https://hastebin.com/nelicopusa.txt

**Comment by linuxdaemon** [comment]
The API that plugin uses was retired awhile ago. I'm planning to remove that plugin until I have time to rewrite it for the new API

**Comment by linuxdaemon** [comment]
Fixed in 4a8f73cd39d92f6c533ba1efc67a07452306c4a1
