### ISSUE TITLE
Feature Request: Grab previous lines

### ISSUE THREAD

**Issue by Compgeke** [snoonetIRC/CloudBot#61]
Unfortunately chat can move quick making .grab difficult to use. Would it be possible to implement a feature to grab a line that was said n lines back (eg, grab 2 username to grab 2 lines back instead of last line)?

**Comment by edwardslabs** [comment]
While that is possible to do I prefer to keep the grab functionality the way it is. Part of the fun of the grab command is that you have to grab the quote quickly.
