### ISSUE TITLE
Feature request:  Send rdv/shane a spider image every time he sends a WALLOPS

### ISSUE THREAD

**Issue by ManyRaptors** [snoonetIRC/CloudBot#62]
Alternative:  Print out the WALLOPS *onto* a picture of a giant spider like memebot does & send it to him.

![send-rdvshane-a-5967ac](https://user-images.githubusercontent.com/14988797/28178941-4720f66e-67ce-11e7-9235-c0a6396a521d.jpg)

**Comment by duckspike** [comment]
This seems to be a good source for the spiders:
http://www.spiders.us/pictures/

I support this feature, as long as I never have to see one of them myself.

**Comment by ghost** [comment]
I concur
