### ISSUE TITLE
.imdb returns "Unknown error" when used

### ISSUE THREAD

**Issue by duckspike** [snoonetIRC/CloudBot#63]
Opening on behalf of ragazor:

Usage of the .imdb command returns "Unknown error" every time. This appears to be because the data source, OMDBAPI, is private and requires an API key for use. I don't see any reference to an API key in the source code.

http://www.omdbapi.com/
https://github.com/snoonetIRC/CloudBot/blob/gonzobot/plugins/imdb.py

**Comment by flotwig** [comment]
It looks like omdbapi is charging for API tokens now. I couldn't find another API that provides the level of detail we need.
