### ISSUE TITLE
.wiki command returns invalid links.

### ISSUE THREAD

**Issue by znuxor** [snoonetIRC/CloudBot#7]
Edit: woops, .wiki

When links contain non-standard characters that need to be encoded, the bot returns links that cannot be opened.
For examples:
.wiki soufflé
.wiki "Women_are_wonderful"_effect
.wiki José

A little bit of investigation seems to suggest that requests.utils.quote at the end of the wikipedia.py plugin file encodes an already encoded URL (since % is encoded as %25). The URL seems to be already encoded in request.text . Not reencoding the (already encoded) url at the end might suffice to solve the issue.

**Comment by edwardslabs** [comment]
Thanks for reporting this, I have pushed 161661a13f7079e4b4f67342f8e59be56f98d01a. URLs are reported correctly now.
