### ISSUE TITLE
whois.py has trouble with "new" tld's

### ISSUE THREAD

**Issue by Violet-Vibes** [snoonetIRC/CloudBot#74]
Such as .date, .party etc

```
File "/home/Cloudbot/Cloudbot/plugins/whois.py", line 33, in whois
    info.append("\x02Registrant\x02: {} - \x02{}\x02".format(data["contacts"]["registrant"]["name"], data["contacts"]["registrant"]["email"]))
TypeError: 'NoneType' object is not subscriptable

```

**Comment by linuxdaemon** [comment]
The code referenced in your traceback doesn't even exist in the current version of [whois.py](https://github.com/snoonetIRC/CloudBot/blob/gonzobot/plugins/whois.py). Please make sure you are running the latest version of the plugin from the stable `gonzobot` branch.
