### ISSUE TITLE
SASL Issue When Connecting

### ISSUE THREAD

**Issue by Techman** [snoonetIRC/CloudBot#75]
I have run into some kind of issue with gonzo recently after doing a `git pull` from the code I used to run months ago. It gets hung up when trying to do SASL authentication.

[pastebin](https://pastebin.com/bFTnVqG4)

**Comment by linuxdaemon** [comment]
According to that log, the server never responds to the `AUTHENTICATE PLAIN` command. If you can produce a raw log by enabling the `raw_file_log` option in the `logging` config block, that will allow us to see the exact commands sent between the server and the bot.
