### ISSUE TITLE
Character code causing issues rendering messages

### ISSUE THREAD

**Issue by johnkernke** [snoonetIRC/CloudBot#8]
The ASCII character "8203" or u'\u200b' (which just looks like a space) causes issues with rendering of a message while using weechat (v1.2 and v1.3 (latest stable as of right now)).

This character is most seen with duckhunt and also herald.

Once the character is in a message it will cut off all text from after that point.

Example:
![gonzobot bug screenshot](https://cloud.githubusercontent.com/assets/618399/9560177/67f5f406-4e4a-11e5-99be-f05e8aab58d8.png)

The first line is a herald, and the second is what happens to a "duck".

**Comment by edwardslabs** [comment]
This is an issue with weechat or your terminal not being able to handle a zero width space. 

http://savannah.nongnu.org/bugs/?40985 - Looks like it is reported to be fixed in weechat 1.4.

**Comment by johnkernke** [comment]
ah, sorry for not searching around enough. might just have to use weechat 1.4 then
