### ISSUE TITLE
Request - Merge / Update Score

### ISSUE THREAD

**Issue by unsangkarable** [snoonetIRC/CloudBot#9]
Hi, i would like to request a feature so that I can merge score for a user that have 2 or 3 nicks. 

For example:
nick1 have scores of 40 kills but sometimes he used nick2 and nick3 for shooting the ducks. And it would be helpful if me (as admin) can update the score for him.

This merge feature should cater to kill and befriend. Thanks!

**Comment by edwardslabs** [comment]
402fd146e0365f71f1bea714ee69362c61f99092 adds this functionality. Be careful though once you transfer someone's score it will not be possible to transfer it back. (no undo).
