### ISSUE TITLE
Error in hook amazon:amazon

### ISSUE THREAD

**Issue by gtwy** [snoonetIRC/CloudBot#96]
Not sure if the plugins are supported or not, but the Amazon plugin does not work.

```
[09:27:01] [INFO] [network:#channel] <user> .amazon U28E590D
[09:27:02] [ERROR] Error in hook amazon:amazon
Traceback (most recent call last):
  File "/home/james/CloudBot/cloudbot/plugin.py", line 376, in _execute_hook
    out = yield from self.bot.loop.run_in_executor(None, self._execute_hook_threaded, hook, event)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/james/CloudBot/cloudbot/plugin.py", line 340, in _execute_hook_threaded
    return hook.function(*parameters)
  File "/home/james/CloudBot/plugins/amazon.py", line 77, in amazon
    price = item.find('span', {'class': ['s-price', 'a-color-price']}).text
AttributeError: 'NoneType' object has no attribute 'text'
```

The offending line in amazon.py:

```python
    price = item.find('span', {'class': ['s-price', 'a-color-price']}).text
```

**Comment by gtwy** [comment]
Seems that it doesn't happen to all Amazon searches, but does happen to many dealing with computer parts.

Example: .amazon Samsung UHD 28

I will try to solve this over the weekend if no one else sees a quick solution

**Comment by linuxdaemon** [comment]
Can you please try to replicate this issue using [this branch](https://github.com/linuxdaemon/CloudBot/tree/gonzobot+api-fixes) it includes more error handling for many of the web based plugins, including the amazon plugin. This may lead to a more informative error message, as I am unable to replicate this issue with the searches you provided on my testing instance

**Comment by gtwy** [comment]
```
[17:00:09] [INFO] [blindfish:#fish] <wx> .amazon samsung
[17:00:11] [INFO] [blindfish] >> PRIVMSG #fish :(wx) [Sponsored]SALE Qi Certified L2 Fast Wireless Charger... ($39.99) - No Ratings - Prime, Free Shipping - https://is.gd/kSMH7M
```

Using a clone of your branch, the bot seems to work fine. However, using the most recent amazon.py from the snoonetIRC branch fails. When running the same command, `item` doesn't have either "s-price" or "s-color-price" classes. I had it output the HTML to see for myself. Here's the applicable part:

```
<span class="a-offscreen">$39.99</span><span aria-hidden="true" class="a-color-base sx-zero-spacing"><span class="sx-price sx-price-large">
<sup class="sx-price-currency">$</sup>
<span class="sx-price-whole">39</span>
<sup class="sx-price-fractional">99</sup>
</span>
```

**Comment by gtwy** [comment]
Looks like you corrected this on line 90.

https://github.com/linuxdaemon/CloudBot/blob/gonzobot%2Bapi-fixes/plugins/amazon.py#L90

**Comment by linuxdaemon** [comment]
That was not my change. Which branch are you running from the snoonetIRC repo?

**Comment by gtwy** [comment]
As I disable almost all of your plugins, I'm running master.

**Comment by gtwy** [comment]
Here is what I have in my amazon.py file right now:

price = item.find('span', {'class': ['s-price', 'a-color-price']}).text

**Comment by linuxdaemon** [comment]
The `master` branch is not updated. The `gonzobot` branch is the primary branch and is the only maintained branch.

**Comment by linuxdaemon** [comment]
Since this issue is fixed in the `gonzobot` branch, this issue is invalid.

**Comment by gtwy** [comment]
To save someone else from having the same trouble, can you please remove unsupported branches from the README? Or at least a disclaimer on it?

**Comment by linuxdaemon** [comment]
This has been done in #112
